/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistbiblioteca;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class ConsultarUsuario extends javax.swing.JInternalFrame {
    
    private Connection con; // guarda informacoes da conexao
    private Statement stm; // guadrda informacoes da instancia de conexao criada
    private ResultSet res; // guarda lista de dados consultados
    
    /**
     * Creates new form ConsultarUsuario
     */
    public ConsultarUsuario() {
        initComponents();
        setTitle("Consulta de usuário");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBconsultar = new javax.swing.JButton();
        jBatualizar = new javax.swing.JButton();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "E-mail", "Telefone", "Data de nascimento", "endereço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBconsultar.setText("Consultar");
        jBconsultar.addActionListener(this::jBconsultarActionPerformed);

        jBatualizar.setText("Atualizar");
        jBatualizar.addActionListener(this::jBatualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jBconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jBatualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBconsultar)
                    .addComponent(jBatualizar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultarActionPerformed
        // TODO add your handling code here:
        try {
            DAO banco = new DAO();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            String comando = "SELECT * FROM usuario;";
      
            model.setNumRows(0);
            res = banco.consultar(comando);
            while(res.next()){
                model.addRow(new Object[]{
                    res.getString("cpf"),
                    res.getString("nome"),
                    res.getString("email"),
                    res.getString("telefone"),
                    res.getString("data_nasc"),
                    res.getString("endereco")
                });
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Erro ao consultar dados");
        }
        
        
 
    }//GEN-LAST:event_jBconsultarActionPerformed

    private void jBatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatualizarActionPerformed
        // TODO add your handling code here:
        
        DAO banco = new DAO();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        String comando = "UPDATE usuario set nome='"+
                 model.getValueAt(jTable1.getSelectedRow(), 1)+
                 "',email='"+model.getValueAt(jTable1.getSelectedRow(),2)+
                "',telefone='"+model.getValueAt(jTable1.getSelectedRow(), 3)+
                "',data_nasc='"+model.getValueAt(jTable1.getSelectedRow(), 4)+
                "',endereco ='"+model.getValueAt(jTable1.getSelectedRow(), 5)+
                "' WHERE cpf='"+
                 model.getValueAt(jTable1.getSelectedRow(), 0)+
                 "';";
       
         banco.atualizar(comando);

        
    }//GEN-LAST:event_jBatualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBatualizar;
    private javax.swing.JButton jBconsultar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
