/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.sistbiblioteca;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author teste123
 */
public class ConsultarLivros extends javax.swing.JInternalFrame {
    private Connection con; // guarda informacoes da conexao
    private Statement stm; // guadrda informacoes da instancia de conexao criada
    private ResultSet res; // guarda lista de dados consultados
    /**
     * Creates new form ConsultarLivros
     */
    public ConsultarLivros() {
        initComponents();
        listarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbCategorias = new javax.swing.JComboBox<>();
        jbConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbAtualizar = new javax.swing.JButton();

        jcbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));

        jbConsultar.setText("Consultar");
        jbConsultar.addActionListener(this::jbConsultarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "ISBN", "Quantidade", "id"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(this::jbAtualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbConsultar)
                        .addGap(75, 75, 75)
                        .addComponent(jbAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultar)
                    .addComponent(jbAtualizar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        try {
            DAO banco = new DAO();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            String comando;
            if(jcbCategorias.getSelectedIndex()==0){
                comando = "SELECT titulo,autor,isbn,quantidade,id FROM livro";
            }else{
                comando = "SELECT titulo,autor,isbn,quantidade,id FROM livro where categoria_id='"+jcbCategorias.getSelectedIndex()+"';";
            }
            model.setNumRows(0);
            res = banco.consultar(comando);
            while(res.next()){
                model.addRow(new Object[]{
                    res.getString("titulo"),
                    res.getString("autor"),
                    res.getString("isbn"),
                    res.getString("quantidade"),
                    res.getString("id")
                });
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Erro ao consultar dados");
        }
        
    }//GEN-LAST:event_jbConsultarActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
       DAO banco = new DAO();
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       String comando = "UPDATE livro set titulo='"+
                model.getValueAt(jTable1.getSelectedRow(), 0)+
                "',autor='"+model.getValueAt(jTable1.getSelectedRow(),1)+
               "',isbn='"+model.getValueAt(jTable1.getSelectedRow(), 2)+
               "',quantidade="+model.getValueAt(jTable1.getSelectedRow(), 3)+
               " WHERE id="+
                model.getValueAt(jTable1.getSelectedRow(), 4)+
                ";";
       //UPDATE livro set titulo='TT', autor='AA' ,isbn='00',quantidade=0 where categoria_id=
        banco.atualizar(comando);
        JOptionPane.showMessageDialog(rootPane,"registro atualizado! ");
    }//GEN-LAST:event_jbAtualizarActionPerformed
    public void listarCategorias(){
            try {
                String comando = "Select * FROM categoria;";
                DAO banco = new DAO();
                res = banco.consultar(comando);
                while(res.next()){
                    jcbCategorias.addItem(res.getString("descricao"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao consultar");
            }
        
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JComboBox<String> jcbCategorias;
    // End of variables declaration//GEN-END:variables
}
