/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.sistbiblioteca;

import javax.swing.JOptionPane;

/**
 *
 * @author afonsvfdeb
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setTitle("Sistema de gerenciamento de bibliotecas");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jBconsultaMain = new javax.swing.JButton();
        jBcadastroMain = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        CadastroU = new javax.swing.JMenuItem();
        CadastroL = new javax.swing.JMenuItem();
        CadastroC = new javax.swing.JMenuItem();
        CadastroE = new javax.swing.JMenuItem();
        CadastroD = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        openMenuItem1 = new javax.swing.JMenuItem();
        saveMenuItem1 = new javax.swing.JMenuItem();
        exitMenuItem1 = new javax.swing.JMenuItem();
        saveAsMenuItem2 = new javax.swing.JMenuItem();
        saveAsMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(91, 84, 84));

        jBconsultaMain.setBackground(new java.awt.Color(0, 0, 0));
        jBconsultaMain.setText("Consultar");
        jBconsultaMain.addActionListener(this::jBconsultaMainActionPerformed);
        desktopPane.add(jBconsultaMain);
        jBconsultaMain.setBounds(380, 120, 120, 30);

        jBcadastroMain.setBackground(new java.awt.Color(0, 0, 0));
        jBcadastroMain.setText("Cadastrar");
        jBcadastroMain.addActionListener(this::jBcadastroMainActionPerformed);
        desktopPane.add(jBcadastroMain);
        jBcadastroMain.setBounds(160, 120, 120, 30);

        jLabel1.setFont(new java.awt.Font("Cantarell", 3, 18)); // NOI18N
        jLabel1.setText("Bem vindo ao gerenciador de bibliotecas!");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(160, 40, 390, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livro.png"))); // NOI18N
        desktopPane.add(jLabel2);
        jLabel2.setBounds(500, 20, 260, 410);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastrar");

        CadastroU.setMnemonic('o');
        CadastroU.setText("Usuário");
        CadastroU.addActionListener(this::CadastroUActionPerformed);
        fileMenu.add(CadastroU);

        CadastroL.setMnemonic('s');
        CadastroL.setText("Livro");
        fileMenu.add(CadastroL);

        CadastroC.setMnemonic('x');
        CadastroC.setText("Categoria");
        CadastroC.addActionListener(this::CadastroCActionPerformed);
        fileMenu.add(CadastroC);

        CadastroE.setMnemonic('a');
        CadastroE.setText("Empréstimo");
        fileMenu.add(CadastroE);

        CadastroD.setMnemonic('a');
        CadastroD.setText("Devolução");
        fileMenu.add(CadastroD);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Consultar");

        openMenuItem1.setMnemonic('o');
        openMenuItem1.setText("Usuário");
        editMenu.add(openMenuItem1);

        saveMenuItem1.setMnemonic('s');
        saveMenuItem1.setText("Livro");
        editMenu.add(saveMenuItem1);

        exitMenuItem1.setMnemonic('x');
        exitMenuItem1.setText("Categoria");
        exitMenuItem1.addActionListener(this::exitMenuItem1ActionPerformed);
        editMenu.add(exitMenuItem1);

        saveAsMenuItem2.setMnemonic('a');
        saveAsMenuItem2.setText("Empréstimo");
        editMenu.add(saveAsMenuItem2);

        saveAsMenuItem3.setMnemonic('a');
        saveAsMenuItem3.setText("Devolução");
        editMenu.add(saveAsMenuItem3);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroCActionPerformed
    }//GEN-LAST:event_CadastroCActionPerformed

    private void exitMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItem1ActionPerformed

    private void CadastroUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroUActionPerformed

        
        CadastroUsuario form = new CadastroUsuario();
        desktopPane.add(form);
        form.setVisible(true);

    }//GEN-LAST:event_CadastroUActionPerformed

    private void jBcadastroMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastroMainActionPerformed

       Integer op = Integer.parseInt(JOptionPane.showInputDialog(null,"O que deseja cadastrar?\n[1] Usuario\n"
                + "[2] Livro\n"
                + "[3] Categoria\n"
                + "[4] Empréstimo\n"
                + "[5] Devolução\n" )) ;
        
       
       if (op != null) { //houve resposta
        switch (op) {
            case 1:
                CadastroUsuario form = new CadastroUsuario();
                desktopPane.add(form);
                form.setVisible(true);                
                break;
                
                case 2:
                CadastrarLivro form1 = new CadastrarLivro();
                desktopPane.add(form1);
                form1.setVisible(true);
                break;
            case 3:
                
                CadastrarCategoria form2 = new CadastrarCategoria();    
                desktopPane.add(form2);
                form2.setVisible(true);
                
                break;
            case 4: //emprestimo
                break;
            case 5: //devolução
                break;
            default:
                JOptionPane.showMessageDialog(null, "Opção inválida!");
        }
       }

    }//GEN-LAST:event_jBcadastroMainActionPerformed

    private void jBconsultaMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultaMainActionPerformed
        
       Integer op = Integer.parseInt(JOptionPane.showInputDialog(null,"O que deseja consultar?\n[1] Usuario\n"
                + "[2] Livro\n"
                + "[3] Categoria\n"
                + "[4] Empréstimo\n"
                + "[5] Devolução\n" )) ;

       if (op != null) { //houve resposta
        switch (op) {
            case 1:
                break;
                
                case 2:
                ConsultarLivros form3 = new ConsultarLivros();
                desktopPane.add(form3);
                form3.setVisible(true);
                 break;
            case 3:
                ConsultarCategoria form4 = new ConsultarCategoria();
                desktopPane.add(form4);
                form4.setVisible(true);
                
                break;
            case 4: //emprestimo
                break;
            case 5: //devolução
                break;
            default:
                JOptionPane.showMessageDialog(null, "Opção inválida!");
        }
       }
       
    }//GEN-LAST:event_jBconsultaMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroC;
    private javax.swing.JMenuItem CadastroD;
    private javax.swing.JMenuItem CadastroE;
    private javax.swing.JMenuItem CadastroL;
    private javax.swing.JMenuItem CadastroU;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem1;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jBcadastroMain;
    private javax.swing.JButton jBconsultaMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem1;
    private javax.swing.JMenuItem saveAsMenuItem2;
    private javax.swing.JMenuItem saveAsMenuItem3;
    private javax.swing.JMenuItem saveMenuItem1;
    // End of variables declaration//GEN-END:variables

}
